spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Joole?characterEncoding=utf-8&useSSL=false
    username: hbstudent
    password: hbstudent
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
